version: "3"
services:
  ssdb-credentials:
    build: "./ssdb"
    volumes:
      - "/var/lib/ssdb"
    restart: always
  ssdb-status:
    build: "./ssdb"
    volumes:
      - "/var/lib/ssdb"
    restart: always
  ssdb-users:
    build: "./ssdb"
    volumes:
      - "/var/lib/ssdb"
    restart: always
  worker:
    build: "./worker"
    depends_on:
      # - "bot"
      - "ssdb-credentials"
      - "ssdb-status"
      - "ssdb-users"
    environment:
      BOT_URL: "bot:12345"
    restart: always
    cap_add:
      - SYS_ADMIN
  bot:
    build: "./bot"
    depends_on:
      - "ssdb-credentials"
      - "ssdb-status"
      - "ssdb-users"
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: "TOKEN_HERE"
  test:
    build: "./test"
    stdin_open: true
    tty: true
  cred:
    build: "./cred"
    depends_on:
      - "ssdb-credentials"
    stdin_open: true
    tty: true
